// <auto-generated />
using System;
using CountersLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CountersLibrary.Migrations
{
    [DbContext(typeof(ApplContext))]
    [Migration("20221026092034_Add Cost entity")]
    partial class AddCostentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CountersLibrary.Cost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ColdSpend")
                        .HasColumnType("integer");

                    b.Property<int>("GasCost")
                        .HasColumnType("integer");

                    b.Property<int>("GasSpend")
                        .HasColumnType("integer");

                    b.Property<int>("HotSpend")
                        .HasColumnType("integer");

                    b.Property<int>("PowerCost")
                        .HasColumnType("integer");

                    b.Property<int>("PowerSpend")
                        .HasColumnType("integer");

                    b.Property<int>("RRecordID")
                        .HasColumnType("integer");

                    b.Property<int>("WaterCost")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("RRecordID");

                    b.ToTable("Cost");
                });

            modelBuilder.Entity("CountersLibrary.Record", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Cold")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Gas")
                        .HasColumnType("integer");

                    b.Property<int>("Hot")
                        .HasColumnType("integer");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Record");
                });

            modelBuilder.Entity("CountersLibrary.Cost", b =>
                {
                    b.HasOne("CountersLibrary.Record", "RRecord")
                        .WithMany()
                        .HasForeignKey("RRecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
